### ISSUE TITLE
Cannot import name world

### ISSUE THREAD

**Issue by navett52** [Fenixin/Minecraft-Region-Fixer#96]
I'm running ubuntu 18.04.2.
When I run 'python --version' it says I'm running python 2.7.15.
I know the walkthrough says this doesn't work with 2.7.x or 3.x but I don't know how to change that or if that's the issue.
Whenever I try to run regionfixer.py it gives this stack trace saying it can't import the world module.

Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/srv/bin/Minecraft-Region-Fixer/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/srv/bin/Minecraft-Region-Fixer/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world

**Comment by navett52** [comment]
Fixed it. Figured out how to run a different version of python and it seems to be working.
